spring:
  datasource:
    url: jdbc:mysql://${DATABASE_SERVER_NAME:192.168.99.101}:3306/dmg_java
    username: ${DATABASE_USER_NAME:java}
    password: ${DATABASE_USER_PASSWORD:1234}
  jpa:
    hibernate:
      # dont do this in production!!
      ddl-auto: update
  lifecycle:
    timeout-per-shutdown-phase: 30s
info:
  app:
    name: monitoramento-glicemia-dmg
    description: Monitoramento da glicemia em grávidas com DMG(Diabetes Mellitus Gestacional)
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,metrics
  health:
    probes:
      enabled: true
server:
  shutdown: graceful
  servlet:
    context-path: /app
